language: cpp

addons:
  apt:
    packages:
    - cmake

compiler:
  - gcc
  
env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "hpKkUFK38ylP0OeHLe5kG/zKDlM5fe3sWjcROQv9i+InAiUUWnnT9LSnFXrutNmq95djjUQKts9SmKMNiFoX/ufJRzqcCSSRCPKtfFhnMVDkG5DFcHqTsfWtyUti98LzNdvS6UPRXQGvI6am74VA54iZI1NzdGqMf8JzpWyXMFeEsMrnZZ8QyvapoYGmDxexLV08QMAAcbxpTjQMDGo/YXoVFBzSEH59AjmgqTjsrZkjm+6TnEoOl658v68xZ7fxEJulDjpJ/6LQ3mHfZ5RXu4/YKWMTd5fYyCy/MlfnREH6hOw3ZqT8DH155Q2jLKJlwQKtausgVU/FqqWiuCMMrVrBtklg7Bx6QafEKn0Gv6KjdwFPKbIzBgJKDb7g45QIs5E8e6M2WVz9ZxH0Fg74thL2oMNyi9Fgpr/hcXOFZYI36AMUssbOM5dx3+NQ4oxP673ZGa4WUrFUpulhLiJ2Rtp6NpPqkCsmHojZQMqfp8yNdxBss4IwJblB9CpCodBucWP2MKigNM/wMyr+lja62/lJM7jFSePfNPuMNec8TdocqdAm+2HgYllCriwnoN+uhy8otynQdlq02slZmmLzapSsRXJv7QRkbsrnpPTcER6tgnjQ77smTicaABOKTSXXJA4lRuuJZ+u3tGAhsQ4OmuBRC+11zMjgm2iuZyNacb4="

addons:
  coverity_scan:
    project:
      name: "azerg/time_from_uuid"
      description: "Build submitted via Travis CI"
    #notification_email: ...
    build_command_prepend: "./configure; make clean"
    build_command:   "make -j 4"
    branch_pattern: coverity_scan
  
before_script:
  - ls -l
  - wget -c 'http://sourceforge.net/projects/boost/files/boost/1.59.0/boost_1_59_0.tar.bz2/download'
  - tar xf download
  - rm download
  - echo '-----boost downloaded & extracted-----'
  - export BOOST_ROOT=$PWD/boost_1_59_0/
  - export GTEST_BUILD_NAME=gtest-1.7.0
  - wget 'http://googletest.googlecode.com/files/'$GTEST_BUILD_NAME'.zip'
  - unzip $GTEST_BUILD_NAME.zip
  - rm $GTEST_BUILD_NAME.zip
  - cd $GTEST_BUILD_NAME/cmake
  - cmake -DBUILD_SHARED_LIBS=ON -Dgtest_build_samples=ON -G"Unix Makefiles" ..
  - make
  - cd ../../
  - echo '-----gtest compiled-----'
  - export GTEST_ROOT=$PWD/gtest-1.7.0/
  - cmake . -B"build" -Wno-dev -DGTEST_ROOT=$GTEST_ROOT -DBOOST_ROOT=$BOOST_ROOT
script:
  - cd build
  - make
  - ./uuidTest
 